export default {
  bid4Skill1:
    "https://drive.google.com/uc?export=view&id=1114cOLCZW_BnM32d_lqOxI8teVbDCi1n",
  bid4Skill2:
    "https://drive.google.com/uc?export=view&id=1IYuNZU8xMsPd_A5oCWwi3gV1-p8QilsV",
  bid4Skill3:
    "https://drive.google.com/uc?export=view&id=1_vh97JgxSl0Lufs8v02NG4wYUiXRTnDg",
  bid4SkillCover:
    "https://drive.google.com/uc?export=view&id=1bwfwBDwOB9Wk5iCvo1PTXmPCz9kdZHI3",
  bridgePay1:
    "https://drive.google.com/uc?export=view&id=1rUHan15nMuJJkj3KP4-iATEp490MXMZT",
  bridgePay2:
    "https://drive.google.com/uc?export=view&id=10S4SC-CXGLUq74x8Nzqg8lDqJvZCow3M",
  bridgePay3:
    "https://drive.google.com/uc?export=view&id=1TaeOdDw2H1SA328i-SR5hP38hqqA_UfW",
  bridgePay4:
    "https://drive.google.com/uc?export=view&id=1EAPLTdwk-QsBTj7bnj9-l0Dt8r3Gv717",
  bridgePay5:
    "https://drive.google.com/uc?export=view&id=1TuTnaavINvjaMHp60mRsQWMzit-5VXm8",
  bridgePay6:
    "https://drive.google.com/uc?export=view&id=18X02B6Y9lP-lQUmE0QP-NRLtUUMFxUHB",
  bridgePay7:
    "https://drive.google.com/uc?export=view&id=1m5Jt2sQWm03O1sWa3vjdZzqfc4Vxu7vk",
  bridgePayCover:
    "https://drive.google.com/uc?export=view&id=1OTNedTwzeALxnmwlq4x2evBZwUEsA_H8",
  briidge2:
    "https://drive.google.com/uc?export=view&id=1-crKtLCCh2Hxp92CUQ3PVeYv93oPnGux",
  briidge3:
    "https://drive.google.com/uc?export=view&id=1ubUDyt2h5m9JyQxDZFK0OfdmyZuRCDAX",
  briidge4:
    "https://drive.google.com/uc?export=view&id=1PEr4apCCt7CRoPXWBVZCVKFJG-ZlPT_8",
  briidge5:
    "https://drive.google.com/uc?export=view&id=1LxS6pmN0VYmeGpPBsdOtOJ5O_yJLgvj7",
  briidge6:
    "https://drive.google.com/uc?export=view&id=1OOjFUcB45EhLBozvdfGUvPwJaDoDc2lL",
  briidge7:
    "https://drive.google.com/uc?export=view&id=1r4ge1ySIZvmHHVWE2kkeDyVJQ9Uq3r7D",
  briidgeGroup6:
    "https://drive.google.com/uc?export=view&id=18XhGaCmNn7mWQi0-Ob369EF_HIWoU993",
  briidgeGroup9:
    "https://drive.google.com/uc?export=view&id=1poUTnrLAbIWdN2kztAK1tWNlRHLbEI4V",
  briidgeGroup9Copy:
    "https://drive.google.com/uc?export=view&id=1k9JDkolRAD_wSfChQT6Tz47qVmm8rUhQ",
  briidgeGroup9Copy2:
    "https://drive.google.com/uc?export=view&id=1Ymm-9GBB6W_yWGi_J2f92WI0sdsX25Mo",
  briidgesection2:
    "https://drive.google.com/uc?export=view&id=1H-1yozUpfoE1PIoAoXQAJDWUubjJ3LTV",
  collabs1:
    "https://drive.google.com/uc?export=view&id=1lH6Dh5HN6Rgl43AWc9rgUu-s6vkzh0eG",
  collabs2:
    "https://drive.google.com/uc?export=view&id=1BHThF75C38B3s1mOShBOb5CQpS467cV3",
  collabs3:
    "https://drive.google.com/uc?export=view&id=1zAWnRk049hSU56QS3-2iXU-eUFSLDku_",
  collabs4:
    "https://drive.google.com/uc?export=view&id=11kDRwvH0D6lmQBisVLjwZVy6mLd8yytJ",
  collabs5:
    "https://drive.google.com/uc?export=view&id=18ktt4N42As1MyVP_8qxjWhn-3YDRZDwH",
  collabs6:
    "https://drive.google.com/uc?export=view&id=1y9Js584B8Zca4fcVTOCPWA3WfNodAnvk",
  collabsCover:
    "https://drive.google.com/uc?export=view&id=1SXQAggSVLpQqaLZePvvA61eOi0PSOEEO",
  connectajob1:
    "https://drive.google.com/uc?export=view&id=13JiCeLhpl2mzZe5rCB7jLzzCPMb-2XC-",
  connectajob10:
    "https://drive.google.com/uc?export=view&id=1pS-RNGvApnN9ICl4NLWWNw11ethXEkLO",
  connectajob2:
    "https://drive.google.com/uc?export=view&id=1puJq9LRK_XCRcGNavAO0su0qqeROgXEZ",
  connectajob3:
    "https://drive.google.com/uc?export=view&id=1y_Cn3KlK_qNIAaLS2E-NPGG5Y1XFtcMB",
  connectajob4:
    "https://drive.google.com/uc?export=view&id=1cuAmZiSKj8Q1c-JJJDBYmsYmxPY0bMEP",
  connectajob5:
    "https://drive.google.com/uc?export=view&id=1RE7AQqo-izTiZ2IoO1tgh-fNUeqexgUF",
  connectajob6:
    "https://drive.google.com/uc?export=view&id=1R3_-5nJTgfM2Xm3SGxfeIZk-tZ2dC2Up",
  connectajob7:
    "https://drive.google.com/uc?export=view&id=1x8XpZjWXZaGfUOkTV6_tE2f08NHvzlmK",
  connectajob8:
    "https://drive.google.com/uc?export=view&id=1HWf-IExtTSowjF-hWCuTCZsZVSkp8Ga_",
  connectajob9:
    "https://drive.google.com/uc?export=view&id=1XbOlLht6rOILIsylW50Gn8WfhCJOUtv1",
  connectajobCover:
    "https://drive.google.com/uc?export=view&id=1Unb8zgXee63sPp8L1EFqhXNYbrfM4v8i",
  corpzap1:
    "https://drive.google.com/uc?export=view&id=1vthmFQWJNEyGOcpVCPUYSnv4wsBzgp54",
  corpzap2:
    "https://drive.google.com/uc?export=view&id=1P7xrOOq2RAB6OaeBSzXRAByYJ-oQ0VLw",
  corpzap3:
    "https://drive.google.com/uc?export=view&id=1voMfIalXLiqhKc6AhzWEUaDExk_sUXdH",
  corpzapCover:
    "https://drive.google.com/uc?export=view&id=1JSks4FCXbe6H5d9KbiRlO-O_xbdAlvRL",
  eyeProtec1:
    "https://drive.google.com/uc?export=view&id=193P_WOWcg7zl91qpC11iynw7DW9OUaQh",
  eyeProtec10:
    "https://drive.google.com/uc?export=view&id=102u9ZtqlJpR_G8MahEy7iKDeLImKtMe4",
  eyeProtec11:
    "https://drive.google.com/uc?export=view&id=1I9LzarZ6K_i4KF77vGihuSxPSNvrTKN2",
  eyeProtec12:
    "https://drive.google.com/uc?export=view&id=1LVyYk0Ry7deBLQxM7BqnMa87HmrI_x3F",
  eyeProtec13:
    "https://drive.google.com/uc?export=view&id=1aZ1qTwZmFRYOJ1CKplJgbBFR6Pt1w9Ix",
  eyeProtec2:
    "https://drive.google.com/uc?export=view&id=1F2_nhrEXe4cQTdqjv9VlApN2shRMeGWs",
  eyeProtec3:
    "https://drive.google.com/uc?export=view&id=1mK0p1K2pixCUQoWiRLGDqxmqvkkyzARI",
  eyeProtec4:
    "https://drive.google.com/uc?export=view&id=1a_WjgXSQN_jYw_cwvqi2Rgm-nzQR15fr",
  eyeProtec5:
    "https://drive.google.com/uc?export=view&id=1FKc451LHV4IKJV-C8TPKfW9BUCw8_CCK",
  eyeProtec6:
    "https://drive.google.com/uc?export=view&id=1sLIP1nC_lVulEUmfEeFP7axS76kTKDh5",
  eyeProtec7:
    "https://drive.google.com/uc?export=view&id=1qq_wtjafEIIVrOHRhKNlTvxCP3YWJ4MA",
  eyeProtec8:
    "https://drive.google.com/uc?export=view&id=1rq1gka9VWT3LS6eHXck46e8Zow5VhSHB",
  eyeProtec9:
    "https://drive.google.com/uc?export=view&id=1B9NWSYdEH1c2fHfg6WSugqyRCODCxsoX",
  eyeProtecCover:
    "https://drive.google.com/uc?export=view&id=13HLzQ-Zv_ou1zHnx9A29VoMP0aWVfXFf",
  findAWealthManager_1:
    "https://drive.google.com/uc?export=view&id=1z5su_wryI1ok7-nLdENNbLQpBQv770Ih",
  findAWealthManager_2:
    "https://drive.google.com/uc?export=view&id=1dhbzmPwM8UPcgEcNULnsugm_Yi6RGzze",
  findAWealthManager_3:
    "https://drive.google.com/uc?export=view&id=1_WN6_6uS-A5t1ULupqVGOWYY6n0ore5G",
  findAWealthManager_4:
    "https://drive.google.com/uc?export=view&id=1F1F6ISUpqUYc-q2_G3TC7hemnWAa9QXh",
  findAWealthManager_5:
    "https://drive.google.com/uc?export=view&id=1GZkUA_dYcWjMhGMJP1OuyqoB69K_MQIh",
  findAWealthManager_6:
    "https://drive.google.com/uc?export=view&id=1GVtoGQIVcahenbbFQxIp91SJbthJ9Bx3",
  findAWealthManager_7:
    "https://drive.google.com/uc?export=view&id=10NaUbOV_TRaR6Sp1O9Lq0Q_KJe7ogaw1",
  findAWealthManager_8:
    "https://drive.google.com/uc?export=view&id=1_747bRX80qenRg9O-LPjNYe9uryRrd3C",
  findAWealthManager_9:
    "https://drive.google.com/uc?export=view&id=1QCO5_JlCxHpUw89qj8lkxOhxKlQ2nTwX",
  findAWealthManager_Cover:
    "https://drive.google.com/uc?export=view&id=1IxYQIkk4HUKPjWKh5zrm6oBMbJ5Crwbw",
  getAssured1:
    "https://drive.google.com/uc?export=view&id=1TIvAY8qN3MG0V8ptyZkYpbg2qQJ7pBRu",
  getAssured2:
    "https://drive.google.com/uc?export=view&id=17C3L2a7koY7BQnL_sltAGBoG2S4M4t4Z",
  getAssured3:
    "https://drive.google.com/uc?export=view&id=19BrKtWQDxaJckwl6rYM_Rd-pDgTrf3q4",
  getAssuredCover:
    "https://drive.google.com/uc?export=view&id=1Gr98l-H78VA12JBrnfZRCbdJH9AYvVTW",
  gig1:
    "https://drive.google.com/uc?export=view&id=1VPkpXUbPmhM7a5nMAbNv2gpQH3nRcjIo",
  gig2:
    "https://drive.google.com/uc?export=view&id=1keoNTGCXIXiFr9Nlck5mo3jEdjmnmq_h",
  gig3:
    "https://drive.google.com/uc?export=view&id=1hAnmMBaQs6Jql0EVSCSi7Lh-xqerQo0o",
  gig4:
    "https://drive.google.com/uc?export=view&id=1PkeYvFZAsI8v1WV10fDAgm_Es0oUiMXD",
  gig5:
    "https://drive.google.com/uc?export=view&id=1_oRqV-k_BrivX004l_duNmGgpRgeKWkn",
  gig6:
    "https://drive.google.com/uc?export=view&id=1PFkLay0YBkafscYq_-3-m8abvBVQFOSs",
  gig7:
    "https://drive.google.com/uc?export=view&id=1QxaPdRH1lIHnrQi4F0zdV9t0mjGunsTU",
  gig8:
    "https://drive.google.com/uc?export=view&id=1dIfPVuGj2MsfU1OKCoUm7MIkBcyofqeh",
  gig9:
    "https://drive.google.com/uc?export=view&id=1DdVEwiF40GQXBr9Ntuu2Tm74k0ZMH2Or",
  gigCover:
    "https://drive.google.com/uc?export=view&id=1XDA3PpZUkOi37GABVnW9JVBlUp_YBUgw",
  glife1:
    "https://drive.google.com/uc?export=view&id=1vfO6616vt3OXUdryx6zAznJLBPy_dcY2",
  glife10:
    "https://drive.google.com/uc?export=view&id=198VLrWMnJ86t02gWorQMvqaXCI0vBNNz",
  glife2:
    "https://drive.google.com/uc?export=view&id=11XQVfZd3VU_OGc4WVwyhQxnGMtF9P7pv",
  glife3:
    "https://drive.google.com/uc?export=view&id=1jMoCbe5IgKY5LaUyma3A047Aukm5hxU1",
  glife4:
    "https://drive.google.com/uc?export=view&id=1yULgHEoM2wMVOsj5yLqQphAjZY3FdgNQ",
  glife5:
    "https://drive.google.com/uc?export=view&id=1-87PIKRd96ZvNeN5sEK9ACg5y3UX2cKg",
  glife6:
    "https://drive.google.com/uc?export=view&id=1VxeNuG6ArKmv24uEcgcZCvXCuRg81GQr",
  glife7:
    "https://drive.google.com/uc?export=view&id=1Je565Be3x-dR7zIiUWH9V__mHblIMiI6",
  glife8:
    "https://drive.google.com/uc?export=view&id=1dI6KnU-rqIzoKsmUE2XPubh2OOjFKfPJ",
  glife9:
    "https://drive.google.com/uc?export=view&id=1r8RSraBXRFkLYZc2iKgomz74LEhwZok5",
  glifeCover:
    "https://drive.google.com/uc?export=view&id=1mxOXPFdfshtw6XWxZTcHLH26Z_bNF6G9",
  homehub1:
    "https://drive.google.com/uc?export=view&id=1anSR-oRs46Xp7pkRnzxM3iivIMPD7FvX",
  homehub10:
    "https://drive.google.com/uc?export=view&id=1r85EkhkF3YbBMym-lfoq9OY75ean9_H-",
  homehub11:
    "https://drive.google.com/uc?export=view&id=1dKt30O2P5BHvdBIPY9VlP-nmKGSTIYoA",
  homehub2:
    "https://drive.google.com/uc?export=view&id=12a2lTnAorjuRRsdkN-7G6rwGTGeRqAuD",
  homehub3:
    "https://drive.google.com/uc?export=view&id=1OphGJdJqMsrTWWrNYaHHsnihmLkkliWf",
  homehub4:
    "https://drive.google.com/uc?export=view&id=1sZWNyz63Uh-K79UKHcFYE-ISeBGb9qXu",
  homehub5:
    "https://drive.google.com/uc?export=view&id=1tv8oAHxbxA79BYppm0iAta7CKgeC0lz3",
  homehub6:
    "https://drive.google.com/uc?export=view&id=1utftgP0vKaxdIdhfcqkKWUys1cgiqDwa",
  homehub7:
    "https://drive.google.com/uc?export=view&id=1nJr7p8qBCuIvR2SF890LqCkZEl8DxhE6",
  homehub8:
    "https://drive.google.com/uc?export=view&id=1BbWzYr5pqLScuqqmAMEHEiOFKI41Vyc4",
  homehub9:
    "https://drive.google.com/uc?export=view&id=1AVuGIQgwklUm8nXZjE9oMbDz1Izk6IWQ",
  homehubCover:
    "https://drive.google.com/uc?export=view&id=1NNLAWVYYFXMMr07ERcwIV-3xu-Xo2hf9",
  luxify1:
    "https://drive.google.com/uc?export=view&id=1n2LIgQWOGO4r-Rky0Y7Khzns9CIaMWox",
  luxify2:
    "https://drive.google.com/uc?export=view&id=1vFvRJIuy5hqtrPSpuFPSF6xTdHSTg2aH",
  luxify3:
    "https://drive.google.com/uc?export=view&id=1bEuwrEpTvCuAN5cNGSgLFT6xTqzijOsS",
  luxify4:
    "https://drive.google.com/uc?export=view&id=12Zo8Upz2zdKQFYDpqRdGupBInRtU3zyZ",
  luxifyCover:
    "https://drive.google.com/uc?export=view&id=1JAa3iRIaOBC43eXxpzJ5Nnz_QdKjX5UP",
  mosendo1:
    "https://drive.google.com/uc?export=view&id=1o5gobusZ_mpsp6TXzfXkEGT3Qf9EMQkI",
  mosendo10:
    "https://drive.google.com/uc?export=view&id=1tXpk2fl6wv72GixsX9G7SaHkJTeYyblS",
  mosendo11:
    "https://drive.google.com/uc?export=view&id=1Yc08zmPklT0JhfRM7JltJMq2uGCAj4Xn",
  mosendo2:
    "https://drive.google.com/uc?export=view&id=1ckmaGcH3kYXetcixpf-MpGbgNh4wnX7I",
  mosendo3:
    "https://drive.google.com/uc?export=view&id=1byCkTP2TMv7snyyE-C4gvBb65rbrFN1M",
  mosendo4:
    "https://drive.google.com/uc?export=view&id=1chywxid8JNRO1uYMy9zKdTc9l2nJScOK",
  mosendo5:
    "https://drive.google.com/uc?export=view&id=1ipjj3wlEhbzODWtEay4i_M63lUgZksUU",
  mosendo6:
    "https://drive.google.com/uc?export=view&id=1gUI-QPOf-Q6S-ipvgOg1gLFYOw37Gpxg",
  mosendo7:
    "https://drive.google.com/uc?export=view&id=1OGzsfEiHE2bYabAKNrzU9VpPg9TISYdi",
  mosendo8:
    "https://drive.google.com/uc?export=view&id=1QpMyETjM1VTX3Ns4_GQVClLuvgT1ew_V",
  mosendo9:
    "https://drive.google.com/uc?export=view&id=1OrA4Rz1mdkqn23fT6tAvHP8rsWtBF_AM",
  mosendoCover:
    "https://drive.google.com/uc?export=view&id=1KpLVKt5RsmGg69HTijah9rDUK0hlzuDq",
  narratrs1:
    "https://drive.google.com/uc?export=view&id=1chTeKScuikihGVwdXob8T4Kz3fP63W15",
  narratrs2:
    "https://drive.google.com/uc?export=view&id=1JKY6ceBpkDNjWgYokmMzVe-MPcaIMVV4",
  narratrs3:
    "https://drive.google.com/uc?export=view&id=1aSdp0blsiAUCZWKZc34-FNIAWkHk3LW5",
  narratrs4:
    "https://drive.google.com/uc?export=view&id=14NHNnBTkXOMwLI06gT1thbp0eQiJSZrk",
  narratrs5:
    "https://drive.google.com/uc?export=view&id=1JNLxi8buk2vRfIoCglZhR8KmnM4zwnPn",
  narratrs6:
    "https://drive.google.com/uc?export=view&id=1LQuRf-sEXIX5NpI1DzVT08BQ8Jq-ep1B",
  narratrs7:
    "https://drive.google.com/uc?export=view&id=1DM4YlYh7sfrEdq-XEZZFRl-jrwvamSUg",
  narratrs8:
    "https://drive.google.com/uc?export=view&id=1XVKAV0HfYMYrPM1lhn-lOwkrfmdsKKaz",
  narratrsCover:
    "https://drive.google.com/uc?export=view&id=1Joe1lBxz5sjzbgFy4E9BYkLRfRHo_YyZ",
  open1:
    "https://drive.google.com/uc?export=view&id=1SKyoeIsOBguoNQK7P6yjNU2ZhzkVY_Q_",
  open10:
    "https://drive.google.com/uc?export=view&id=1mLYZh5m2O0R8c5KDiTEfLsl66P_e18cX",
  open11:
    "https://drive.google.com/uc?export=view&id=1h56XnfKSyX4jdO-_6keLBUmWU8fE7Mm9",
  open12:
    "https://drive.google.com/uc?export=view&id=1QoHREJnvk2_Cn_ssmFsM8-RWRacpClMt",
  open13:
    "https://drive.google.com/uc?export=view&id=1LD9QLL--kIQhgv7-TnFQ2LysbQkl5gYe",
  open14:
    "https://drive.google.com/uc?export=view&id=1AxTWxd_lmVUQpR3L4xEhM4KqY-mBw6eA",
  open15:
    "https://drive.google.com/uc?export=view&id=1ElaHRQI73WrExB2pLG90MVff9Wb4L7Ni",
  open16:
    "https://drive.google.com/uc?export=view&id=1qCFZ-Jr50BPAaA4SL7UXAgcA14DvfB-C",
  open2:
    "https://drive.google.com/uc?export=view&id=1cGWkVmn2AQAwI-_GjzyfsP-jDX9c4UFt",
  open3:
    "https://drive.google.com/uc?export=view&id=1vw7an68BytgnespR2VPZ0ANC5FmiDzcF",
  open4:
    "https://drive.google.com/uc?export=view&id=1w_COWIfnkxLuEMR0iXSDa2ECuGkpTNv2",
  open5:
    "https://drive.google.com/uc?export=view&id=15QsRkcJO7lJ-tOap-dbV1QEt3zV_J21u",
  open6:
    "https://drive.google.com/uc?export=view&id=1XNSxoC7KGcM2TOWdnyUMkXY73gY_PRJm",
  open7:
    "https://drive.google.com/uc?export=view&id=1-mqrLpJ3LAIFzGlbFyHmNGqfL8Ywvf_d",
  open8:
    "https://drive.google.com/uc?export=view&id=1eIg8UJk3g6gpuP8ZDgXp4CLC8TslOgB_",
  open9:
    "https://drive.google.com/uc?export=view&id=1-MhVgcg6xDfZpcRM7JvEbhOOk7xUGiTm",
  openCover:
    "https://drive.google.com/uc?export=view&id=1OtnGj9oRjvbci9VKGeOE5fXm3shVg1W2",
  personifi1:
    "https://drive.google.com/uc?export=view&id=1Dv79tYGWg0f2KcvkTdz9nK_W0DAPck7z",
  personifi10:
    "https://drive.google.com/uc?export=view&id=14qzvVeR9hd2zGiW9jL8ljd_JoP1_LpwK",
  personifi11:
    "https://drive.google.com/uc?export=view&id=10vmtvEwLNmgQa7GGgkqHkZNMHSLeyQw_",
  personifi2:
    "https://drive.google.com/uc?export=view&id=1GIu1QWdUL5KuKZ6GWpJTQdIBuZt0XO8F",
  personifi3:
    "https://drive.google.com/uc?export=view&id=1cCLUTt5GENRBjF2nEmVKVileSBMMS-iA",
  personifi4:
    "https://drive.google.com/uc?export=view&id=1ap5svGJkX6CFAGOQP0njpKFVAGxuJ3Hu",
  personifi5:
    "https://drive.google.com/uc?export=view&id=1jEIs9ga6mq7WT6AZ7jA9GOjvX3WWlC72",
  personifi6:
    "https://drive.google.com/uc?export=view&id=15N79xD3G9zFaOD6mer5HL3w2uH_ILisS",
  personifi7:
    "https://drive.google.com/uc?export=view&id=1w_qQ4r73FlZhk79FLxGOL0Kru6JrVus3",
  personifi8:
    "https://drive.google.com/uc?export=view&id=1RtMiik_ijbn7Gn_islazvyqcUFFIaqG-",
  personifi9:
    "https://drive.google.com/uc?export=view&id=1pIiWL88gnK1aaNFsHpLfGl7OeEC3DK3W",
  personifiCover:
    "https://drive.google.com/uc?export=view&id=1y44sZmNXS1kreNlvOZrPUkTMwsrg9_by",
  publicInsight1:
    "https://drive.google.com/uc?export=view&id=1gVK_Al2p0XZXfsBEggy4zhMzf3zks-du",
  publicInsight2:
    "https://drive.google.com/uc?export=view&id=1HJTEQ_Ey7NvoUUlkB-qVvB9x9e8kT6y5",
  publicInsight3:
    "https://drive.google.com/uc?export=view&id=1-60QSfOzFGk73xeBPaFrSscm9wG9de-V",
  publicInsight4:
    "https://drive.google.com/uc?export=view&id=1TcUPPOdk_EiAs_ZhkfSPTJhCOLmbi2-E",
  publicInsight5:
    "https://drive.google.com/uc?export=view&id=1sbvc1QM6EHNl_gBa2vBI2K6q9qn7Sk84",
  publicInsightCover:
    "https://drive.google.com/uc?export=view&id=11wTD0FxbMQNQo2XLzcFgQE8cEqnO-lMU",
  referralCandy1:
    "https://drive.google.com/uc?export=view&id=1bonaL0LFcEoEJWBbIjG8TYAYWqh7usvp",
  referralCandy2:
    "https://drive.google.com/uc?export=view&id=1KMZrIOdLf_DUCMPk5jzA9oYZcy0hOxx3",
  referralCandy3:
    "https://drive.google.com/uc?export=view&id=17fRiaU06BytlNghlkk4_a1KSgyiJ1jHL",
  referralCandy4:
    "https://drive.google.com/uc?export=view&id=1Mf-9_DfimSf2Sl2fqej7KaFpmTihROMr",
  referralCandyCover:
    "https://drive.google.com/uc?export=view&id=1v3sYzSnvo5NWuCu3YRBExJO2fRJHGYRI",
  techsauce1:
    "https://drive.google.com/uc?export=view&id=1imSjqCr7yjieq4HMkrgGaz5tFxUu9PzH",
  techsauce2:
    "https://drive.google.com/uc?export=view&id=1nJI7Wjzn7_l3EYxky49yq5-lbQv7xas9",
  techsauce3:
    "https://drive.google.com/uc?export=view&id=1Kj6K8SLoONfmYpBHsUJkBuD2J2ZPh9lf",
  techsauce4:
    "https://drive.google.com/uc?export=view&id=1Rr-r--FVXcVdbga1R6_iHIjPtlnoh1sA",
  techsauceCover:
    "https://drive.google.com/uc?export=view&id=1Q3ztuhxdPXVBD1GvktwFZEI3uet6rt0_",
  theLuxeNomad1:
    "https://drive.google.com/uc?export=view&id=1rDT1cHKkinse8lhwty1BkDIv6zXlsu6d",
  theLuxeNomad2:
    "https://drive.google.com/uc?export=view&id=1KJWH0O1Ge7Zp1EDhiX-3hHZ1ex-hPxhy",
  theLuxeNomad3:
    "https://drive.google.com/uc?export=view&id=1zCQ327ijdftGJ3oGU1fxG722r-y0XPIt",
  theLuxeNomad4:
    "https://drive.google.com/uc?export=view&id=1RdThw8xyzgqeS0w4xURn5S3HqcEaUuVe",
  theLuxeNomad5:
    "https://drive.google.com/uc?export=view&id=1hlNFf_Pk5YCus9NkzpFX2xXYsdsSjITT",
  theLuxeNomad6:
    "https://drive.google.com/uc?export=view&id=1uxLtmfomzNYuO7_scKGXyBgSFeP8XqKh",
  theLuxeNomadCover:
    "https://drive.google.com/uc?export=view&id=1Em24ve1qrFbx3hK-WmzAEAK8lk7LCn9I",
  twp1:
    "https://drive.google.com/uc?export=view&id=1ZikcpPiT8uMyGSRZ3-D6gWOC_dGFYWA7",
  twp2:
    "https://drive.google.com/uc?export=view&id=1JrWS81Uch9tGAR2w7ivI-IrkqMENhdyJ",
  twp3:
    "https://drive.google.com/uc?export=view&id=1tQEBnTsMojFqrTfumNsshfZIuS6BmiED",
  twp4:
    "https://drive.google.com/uc?export=view&id=1d9-Gx-BiPfDwgR1Au3xRiKeSfy8qYa7t",
  twpCover:
    "https://drive.google.com/uc?export=view&id=1sWJFONSh63lyO38ndrP12PFcKPEgAv16"
};
